/**
 * this code is generated by:
 * const protobuf = require('protobufjs')
   const fs = require('fs')
   // dm.proto from https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/grpc_api/bilibili/community/service/dm/v1/dm.proto
   const root = protobuf.loadSync('dm.proto')
   fs.writeFileSync('dm.json', JSON.stringify(root.toJSON(), null, 2))
 */
export default {
  nested: {
    bilibili: {
      nested: {
        community: {
          nested: {
            service: {
              nested: {
                dm: {
                  nested: {
                    v1: {
                      nested: {
                        DM: {
                          methods: {
                            DmSegMobile: {
                              requestType: 'DmSegMobileReq',
                              responseType: 'DmSegMobileReply',
                            },
                            DmView: {
                              requestType: 'DmViewReq',
                              responseType: 'DmViewReply',
                            },
                            DmPlayerConfig: {
                              requestType: 'DmPlayerConfigReq',
                              responseType: 'Response',
                            },
                            DmSegOtt: {
                              requestType: 'DmSegOttReq',
                              responseType: 'DmSegOttReply',
                            },
                            DmSegSDK: {
                              requestType: 'DmSegSDKReq',
                              responseType: 'DmSegSDKReply',
                            },
                            DmExpoReport: {
                              requestType: 'DmExpoReportReq',
                              responseType: 'DmExpoReportRes',
                            },
                          },
                        },
                        Avatar: {
                          fields: {
                            id: {
                              type: 'string',
                              id: 1,
                            },
                            url: {
                              type: 'string',
                              id: 2,
                            },
                            avatarType: {
                              type: 'AvatarType',
                              id: 3,
                            },
                          },
                        },
                        AvatarType: {
                          values: {
                            AvatarTypeNone: 0,
                            AvatarTypeNFT: 1,
                          },
                        },
                        Bubble: {
                          fields: {
                            text: {
                              type: 'string',
                              id: 1,
                            },
                            url: {
                              type: 'string',
                              id: 2,
                            },
                          },
                        },
                        BubbleType: {
                          values: {
                            BubbleTypeNone: 0,
                            BubbleTypeClickButton: 1,
                            BubbleTypeDmSettingPanel: 2,
                          },
                        },
                        BubbleV2: {
                          fields: {
                            text: {
                              type: 'string',
                              id: 1,
                            },
                            url: {
                              type: 'string',
                              id: 2,
                            },
                            bubbleType: {
                              type: 'BubbleType',
                              id: 3,
                            },
                            exposureOnce: {
                              type: 'bool',
                              id: 4,
                            },
                            exposureType: {
                              type: 'ExposureType',
                              id: 5,
                            },
                          },
                        },
                        Button: {
                          fields: {
                            text: {
                              type: 'string',
                              id: 1,
                            },
                            action: {
                              type: 'int32',
                              id: 2,
                            },
                          },
                        },
                        BuzzwordConfig: {
                          fields: {
                            keywords: {
                              rule: 'repeated',
                              type: 'BuzzwordShowConfig',
                              id: 1,
                            },
                          },
                        },
                        BuzzwordShowConfig: {
                          fields: {
                            name: {
                              type: 'string',
                              id: 1,
                            },
                            schema: {
                              type: 'string',
                              id: 2,
                            },
                            source: {
                              type: 'int32',
                              id: 3,
                            },
                            id: {
                              type: 'int64',
                              id: 4,
                            },
                            buzzwordId: {
                              type: 'int64',
                              id: 5,
                            },
                            schemaType: {
                              type: 'int32',
                              id: 6,
                            },
                          },
                        },
                        CheckBox: {
                          fields: {
                            text: {
                              type: 'string',
                              id: 1,
                            },
                            type: {
                              type: 'CheckboxType',
                              id: 2,
                            },
                            defaultValue: {
                              type: 'bool',
                              id: 3,
                            },
                            show: {
                              type: 'bool',
                              id: 4,
                            },
                          },
                        },
                        CheckboxType: {
                          values: {
                            CheckboxTypeNone: 0,
                            CheckboxTypeEncourage: 1,
                            CheckboxTypeColorDM: 2,
                          },
                        },
                        CheckBoxV2: {
                          fields: {
                            text: {
                              type: 'string',
                              id: 1,
                            },
                            type: {
                              type: 'int32',
                              id: 2,
                            },
                            defaultValue: {
                              type: 'bool',
                              id: 3,
                            },
                          },
                        },
                        ClickButton: {
                          fields: {
                            portraitText: {
                              rule: 'repeated',
                              type: 'string',
                              id: 1,
                            },
                            landscapeText: {
                              rule: 'repeated',
                              type: 'string',
                              id: 2,
                            },
                            portraitTextFocus: {
                              rule: 'repeated',
                              type: 'string',
                              id: 3,
                            },
                            landscapeTextFocus: {
                              rule: 'repeated',
                              type: 'string',
                              id: 4,
                            },
                            renderType: {
                              type: 'RenderType',
                              id: 5,
                            },
                            show: {
                              type: 'bool',
                              id: 6,
                            },
                            bubble: {
                              type: 'Bubble',
                              id: 7,
                            },
                          },
                        },
                        ClickButtonV2: {
                          fields: {
                            portraitText: {
                              rule: 'repeated',
                              type: 'string',
                              id: 1,
                            },
                            landscapeText: {
                              rule: 'repeated',
                              type: 'string',
                              id: 2,
                            },
                            portraitTextFocus: {
                              rule: 'repeated',
                              type: 'string',
                              id: 3,
                            },
                            landscapeTextFocus: {
                              rule: 'repeated',
                              type: 'string',
                              id: 4,
                            },
                            renderType: {
                              type: 'int32',
                              id: 5,
                            },
                            textInputPost: {
                              type: 'bool',
                              id: 6,
                            },
                            exposureOnce: {
                              type: 'bool',
                              id: 7,
                            },
                            exposureType: {
                              type: 'int32',
                              id: 8,
                            },
                          },
                        },
                        CommandDm: {
                          fields: {
                            id: {
                              type: 'int64',
                              id: 1,
                            },
                            oid: {
                              type: 'int64',
                              id: 2,
                            },
                            mid: {
                              type: 'string',
                              id: 3,
                            },
                            command: {
                              type: 'string',
                              id: 4,
                            },
                            content: {
                              type: 'string',
                              id: 5,
                            },
                            progress: {
                              type: 'int32',
                              id: 6,
                            },
                            ctime: {
                              type: 'string',
                              id: 7,
                            },
                            mtime: {
                              type: 'string',
                              id: 8,
                            },
                            extra: {
                              type: 'string',
                              id: 9,
                            },
                            idStr: {
                              type: 'string',
                              id: 10,
                            },
                          },
                        },
                        DanmakuAIFlag: {
                          fields: {
                            dmFlags: {
                              rule: 'repeated',
                              type: 'DanmakuFlag',
                              id: 1,
                            },
                          },
                        },
                        DanmakuElem: {
                          fields: {
                            id: {
                              type: 'int64',
                              id: 1,
                            },
                            progress: {
                              type: 'int32',
                              id: 2,
                            },
                            mode: {
                              type: 'int32',
                              id: 3,
                            },
                            fontsize: {
                              type: 'int32',
                              id: 4,
                            },
                            color: {
                              type: 'uint32',
                              id: 5,
                            },
                            midHash: {
                              type: 'string',
                              id: 6,
                            },
                            content: {
                              type: 'string',
                              id: 7,
                            },
                            ctime: {
                              type: 'int64',
                              id: 8,
                            },
                            weight: {
                              type: 'int32',
                              id: 9,
                            },
                            action: {
                              type: 'string',
                              id: 10,
                            },
                            pool: {
                              type: 'int32',
                              id: 11,
                            },
                            idStr: {
                              type: 'string',
                              id: 12,
                            },
                            attr: {
                              type: 'int32',
                              id: 13,
                            },
                            animation: {
                              type: 'string',
                              id: 22,
                            },
                            colorful: {
                              type: 'DmColorfulType',
                              id: 24,
                            },
                          },
                        },
                        DanmakuFlag: {
                          fields: {
                            dmid: {
                              type: 'int64',
                              id: 1,
                            },
                            flag: {
                              type: 'uint32',
                              id: 2,
                            },
                          },
                        },
                        DanmakuFlagConfig: {
                          fields: {
                            recFlag: {
                              type: 'int32',
                              id: 1,
                            },
                            recText: {
                              type: 'string',
                              id: 2,
                            },
                            recSwitch: {
                              type: 'int32',
                              id: 3,
                            },
                          },
                        },
                        DanmuDefaultPlayerConfig: {
                          fields: {
                            playerDanmakuUseDefaultConfig: {
                              type: 'bool',
                              id: 1,
                            },
                            playerDanmakuAiRecommendedSwitch: {
                              type: 'bool',
                              id: 4,
                            },
                            playerDanmakuAiRecommendedLevel: {
                              type: 'int32',
                              id: 5,
                            },
                            playerDanmakuBlocktop: {
                              type: 'bool',
                              id: 6,
                            },
                            playerDanmakuBlockscroll: {
                              type: 'bool',
                              id: 7,
                            },
                            playerDanmakuBlockbottom: {
                              type: 'bool',
                              id: 8,
                            },
                            playerDanmakuBlockcolorful: {
                              type: 'bool',
                              id: 9,
                            },
                            playerDanmakuBlockrepeat: {
                              type: 'bool',
                              id: 10,
                            },
                            playerDanmakuBlockspecial: {
                              type: 'bool',
                              id: 11,
                            },
                            playerDanmakuOpacity: {
                              type: 'float',
                              id: 12,
                            },
                            playerDanmakuScalingfactor: {
                              type: 'float',
                              id: 13,
                            },
                            playerDanmakuDomain: {
                              type: 'float',
                              id: 14,
                            },
                            playerDanmakuSpeed: {
                              type: 'int32',
                              id: 15,
                            },
                            inlinePlayerDanmakuSwitch: {
                              type: 'bool',
                              id: 16,
                            },
                            playerDanmakuSeniorModeSwitch: {
                              type: 'int32',
                              id: 17,
                            },
                            playerDanmakuAiRecommendedLevelV2: {
                              type: 'int32',
                              id: 18,
                            },
                            playerDanmakuAiRecommendedLevelV2Map: {
                              keyType: 'int32',
                              type: 'int32',
                              id: 19,
                            },
                          },
                        },
                        DanmuPlayerConfig: {
                          fields: {
                            playerDanmakuSwitch: {
                              type: 'bool',
                              id: 1,
                            },
                            playerDanmakuSwitchSave: {
                              type: 'bool',
                              id: 2,
                            },
                            playerDanmakuUseDefaultConfig: {
                              type: 'bool',
                              id: 3,
                            },
                            playerDanmakuAiRecommendedSwitch: {
                              type: 'bool',
                              id: 4,
                            },
                            playerDanmakuAiRecommendedLevel: {
                              type: 'int32',
                              id: 5,
                            },
                            playerDanmakuBlocktop: {
                              type: 'bool',
                              id: 6,
                            },
                            playerDanmakuBlockscroll: {
                              type: 'bool',
                              id: 7,
                            },
                            playerDanmakuBlockbottom: {
                              type: 'bool',
                              id: 8,
                            },
                            playerDanmakuBlockcolorful: {
                              type: 'bool',
                              id: 9,
                            },
                            playerDanmakuBlockrepeat: {
                              type: 'bool',
                              id: 10,
                            },
                            playerDanmakuBlockspecial: {
                              type: 'bool',
                              id: 11,
                            },
                            playerDanmakuOpacity: {
                              type: 'float',
                              id: 12,
                            },
                            playerDanmakuScalingfactor: {
                              type: 'float',
                              id: 13,
                            },
                            playerDanmakuDomain: {
                              type: 'float',
                              id: 14,
                            },
                            playerDanmakuSpeed: {
                              type: 'int32',
                              id: 15,
                            },
                            playerDanmakuEnableblocklist: {
                              type: 'bool',
                              id: 16,
                            },
                            inlinePlayerDanmakuSwitch: {
                              type: 'bool',
                              id: 17,
                            },
                            inlinePlayerDanmakuConfig: {
                              type: 'int32',
                              id: 18,
                            },
                            playerDanmakuIosSwitchSave: {
                              type: 'int32',
                              id: 19,
                            },
                            playerDanmakuSeniorModeSwitch: {
                              type: 'int32',
                              id: 20,
                            },
                            playerDanmakuAiRecommendedLevelV2: {
                              type: 'int32',
                              id: 21,
                            },
                            playerDanmakuAiRecommendedLevelV2Map: {
                              keyType: 'int32',
                              type: 'int32',
                              id: 22,
                            },
                          },
                        },
                        DanmuPlayerConfigPanel: {
                          fields: {
                            selectionText: {
                              type: 'string',
                              id: 1,
                            },
                          },
                        },
                        DanmuPlayerDynamicConfig: {
                          fields: {
                            progress: {
                              type: 'int32',
                              id: 1,
                            },
                            playerDanmakuDomain: {
                              type: 'float',
                              id: 14,
                            },
                          },
                        },
                        DanmuPlayerViewConfig: {
                          fields: {
                            danmukuDefaultPlayerConfig: {
                              type: 'DanmuDefaultPlayerConfig',
                              id: 1,
                            },
                            danmukuPlayerConfig: {
                              type: 'DanmuPlayerConfig',
                              id: 2,
                            },
                            danmukuPlayerDynamicConfig: {
                              rule: 'repeated',
                              type: 'DanmuPlayerDynamicConfig',
                              id: 3,
                            },
                            danmukuPlayerConfigPanel: {
                              type: 'DanmuPlayerConfigPanel',
                              id: 4,
                            },
                          },
                        },
                        DanmuWebPlayerConfig: {
                          fields: {
                            dmSwitch: {
                              type: 'bool',
                              id: 1,
                            },
                            aiSwitch: {
                              type: 'bool',
                              id: 2,
                            },
                            aiLevel: {
                              type: 'int32',
                              id: 3,
                            },
                            blocktop: {
                              type: 'bool',
                              id: 4,
                            },
                            blockscroll: {
                              type: 'bool',
                              id: 5,
                            },
                            blockbottom: {
                              type: 'bool',
                              id: 6,
                            },
                            blockcolor: {
                              type: 'bool',
                              id: 7,
                            },
                            blockspecial: {
                              type: 'bool',
                              id: 8,
                            },
                            preventshade: {
                              type: 'bool',
                              id: 9,
                            },
                            dmask: {
                              type: 'bool',
                              id: 10,
                            },
                            opacity: {
                              type: 'float',
                              id: 11,
                            },
                            dmarea: {
                              type: 'int32',
                              id: 12,
                            },
                            speedplus: {
                              type: 'float',
                              id: 13,
                            },
                            fontsize: {
                              type: 'float',
                              id: 14,
                            },
                            screensync: {
                              type: 'bool',
                              id: 15,
                            },
                            speedsync: {
                              type: 'bool',
                              id: 16,
                            },
                            fontfamily: {
                              type: 'string',
                              id: 17,
                            },
                            bold: {
                              type: 'bool',
                              id: 18,
                            },
                            fontborder: {
                              type: 'int32',
                              id: 19,
                            },
                            drawType: {
                              type: 'string',
                              id: 20,
                            },
                            seniorModeSwitch: {
                              type: 'int32',
                              id: 21,
                            },
                            aiLevelV2: {
                              type: 'int32',
                              id: 22,
                            },
                            aiLevelV2Map: {
                              keyType: 'int32',
                              type: 'int32',
                              id: 23,
                            },
                          },
                        },
                        DMAttrBit: {
                          values: {
                            DMAttrBitProtect: 0,
                            DMAttrBitFromLive: 1,
                            DMAttrHighLike: 2,
                          },
                        },
                        DmColorful: {
                          fields: {
                            type: {
                              type: 'DmColorfulType',
                              id: 1,
                            },
                            src: {
                              type: 'string',
                              id: 2,
                            },
                          },
                        },
                        DmColorfulType: {
                          values: {
                            NoneType: 0,
                            VipGradualColor: 60001,
                          },
                        },
                        DmExpoReportReq: {
                          fields: {
                            sessionId: {
                              type: 'string',
                              id: 1,
                            },
                            oid: {
                              type: 'int64',
                              id: 2,
                            },
                            spmid: {
                              type: 'string',
                              id: 4,
                            },
                          },
                        },
                        DmExpoReportRes: {
                          fields: {},
                        },
                        DmPlayerConfigReq: {
                          fields: {
                            ts: {
                              type: 'int64',
                              id: 1,
                            },
                            switch: {
                              type: 'PlayerDanmakuSwitch',
                              id: 2,
                            },
                            switchSave: {
                              type: 'PlayerDanmakuSwitchSave',
                              id: 3,
                            },
                            useDefaultConfig: {
                              type: 'PlayerDanmakuUseDefaultConfig',
                              id: 4,
                            },
                            aiRecommendedSwitch: {
                              type: 'PlayerDanmakuAiRecommendedSwitch',
                              id: 5,
                            },
                            aiRecommendedLevel: {
                              type: 'PlayerDanmakuAiRecommendedLevel',
                              id: 6,
                            },
                            blocktop: {
                              type: 'PlayerDanmakuBlocktop',
                              id: 7,
                            },
                            blockscroll: {
                              type: 'PlayerDanmakuBlockscroll',
                              id: 8,
                            },
                            blockbottom: {
                              type: 'PlayerDanmakuBlockbottom',
                              id: 9,
                            },
                            blockcolorful: {
                              type: 'PlayerDanmakuBlockcolorful',
                              id: 10,
                            },
                            blockrepeat: {
                              type: 'PlayerDanmakuBlockrepeat',
                              id: 11,
                            },
                            blockspecial: {
                              type: 'PlayerDanmakuBlockspecial',
                              id: 12,
                            },
                            opacity: {
                              type: 'PlayerDanmakuOpacity',
                              id: 13,
                            },
                            scalingfactor: {
                              type: 'PlayerDanmakuScalingfactor',
                              id: 14,
                            },
                            domain: {
                              type: 'PlayerDanmakuDomain',
                              id: 15,
                            },
                            speed: {
                              type: 'PlayerDanmakuSpeed',
                              id: 16,
                            },
                            enableblocklist: {
                              type: 'PlayerDanmakuEnableblocklist',
                              id: 17,
                            },
                            inlinePlayerDanmakuSwitch: {
                              type: 'InlinePlayerDanmakuSwitch',
                              id: 18,
                            },
                            seniorModeSwitch: {
                              type: 'PlayerDanmakuSeniorModeSwitch',
                              id: 19,
                            },
                            aiRecommendedLevelV2: {
                              type: 'PlayerDanmakuAiRecommendedLevelV2',
                              id: 20,
                            },
                          },
                        },
                        DmSegConfig: {
                          fields: {
                            pageSize: {
                              type: 'int64',
                              id: 1,
                            },
                            total: {
                              type: 'int64',
                              id: 2,
                            },
                          },
                        },
                        DmSegMobileReply: {
                          fields: {
                            elems: {
                              rule: 'repeated',
                              type: 'DanmakuElem',
                              id: 1,
                            },
                            state: {
                              type: 'int32',
                              id: 2,
                            },
                            aiFlag: {
                              type: 'DanmakuAIFlag',
                              id: 3,
                            },
                            colorfulSrc: {
                              rule: 'repeated',
                              type: 'DmColorful',
                              id: 5,
                            },
                          },
                        },
                        DmSegMobileReq: {
                          fields: {
                            pid: {
                              type: 'int64',
                              id: 1,
                            },
                            oid: {
                              type: 'int64',
                              id: 2,
                            },
                            type: {
                              type: 'int32',
                              id: 3,
                            },
                            segmentIndex: {
                              type: 'int64',
                              id: 4,
                            },
                            teenagersMode: {
                              type: 'int32',
                              id: 5,
                            },
                            ps: {
                              type: 'int64',
                              id: 6,
                            },
                            pe: {
                              type: 'int64',
                              id: 7,
                            },
                            pullMode: {
                              type: 'int32',
                              id: 8,
                            },
                            fromScene: {
                              type: 'int32',
                              id: 9,
                            },
                          },
                        },
                        DmSegOttReply: {
                          fields: {
                            closed: {
                              type: 'bool',
                              id: 1,
                            },
                            elems: {
                              rule: 'repeated',
                              type: 'DanmakuElem',
                              id: 2,
                            },
                          },
                        },
                        DmSegOttReq: {
                          fields: {
                            pid: {
                              type: 'int64',
                              id: 1,
                            },
                            oid: {
                              type: 'int64',
                              id: 2,
                            },
                            type: {
                              type: 'int32',
                              id: 3,
                            },
                            segmentIndex: {
                              type: 'int64',
                              id: 4,
                            },
                          },
                        },
                        DmSegSDKReply: {
                          fields: {
                            closed: {
                              type: 'bool',
                              id: 1,
                            },
                            elems: {
                              rule: 'repeated',
                              type: 'DanmakuElem',
                              id: 2,
                            },
                          },
                        },
                        DmSegSDKReq: {
                          fields: {
                            pid: {
                              type: 'int64',
                              id: 1,
                            },
                            oid: {
                              type: 'int64',
                              id: 2,
                            },
                            type: {
                              type: 'int32',
                              id: 3,
                            },
                            segmentIndex: {
                              type: 'int64',
                              id: 4,
                            },
                          },
                        },
                        DmViewReply: {
                          fields: {
                            closed: {
                              type: 'bool',
                              id: 1,
                            },
                            mask: {
                              type: 'VideoMask',
                              id: 2,
                            },
                            subtitle: {
                              type: 'VideoSubtitle',
                              id: 3,
                            },
                            specialDms: {
                              rule: 'repeated',
                              type: 'string',
                              id: 4,
                            },
                            aiFlag: {
                              type: 'DanmakuFlagConfig',
                              id: 5,
                            },
                            playerConfig: {
                              type: 'DanmuPlayerViewConfig',
                              id: 6,
                            },
                            sendBoxStyle: {
                              type: 'int32',
                              id: 7,
                            },
                            allow: {
                              type: 'bool',
                              id: 8,
                            },
                            checkBox: {
                              type: 'string',
                              id: 9,
                            },
                            checkBoxShowMsg: {
                              type: 'string',
                              id: 10,
                            },
                            textPlaceholder: {
                              type: 'string',
                              id: 11,
                            },
                            inputPlaceholder: {
                              type: 'string',
                              id: 12,
                            },
                            reportFilterContent: {
                              rule: 'repeated',
                              type: 'string',
                              id: 13,
                            },
                            expoReport: {
                              type: 'ExpoReport',
                              id: 14,
                            },
                            buzzwordConfig: {
                              type: 'BuzzwordConfig',
                              id: 15,
                            },
                            expressions: {
                              rule: 'repeated',
                              type: 'Expressions',
                              id: 16,
                            },
                            postPanel: {
                              rule: 'repeated',
                              type: 'PostPanel',
                              id: 17,
                            },
                            activityMeta: {
                              rule: 'repeated',
                              type: 'string',
                              id: 18,
                            },
                            postPanel2: {
                              rule: 'repeated',
                              type: 'PostPanelV2',
                              id: 19,
                            },
                          },
                        },
                        DmViewReq: {
                          fields: {
                            pid: {
                              type: 'int64',
                              id: 1,
                            },
                            oid: {
                              type: 'int64',
                              id: 2,
                            },
                            type: {
                              type: 'int32',
                              id: 3,
                            },
                            spmid: {
                              type: 'string',
                              id: 4,
                            },
                            isHardBoot: {
                              type: 'int32',
                              id: 5,
                            },
                          },
                        },
                        DmWebViewReply: {
                          fields: {
                            state: {
                              type: 'int32',
                              id: 1,
                            },
                            text: {
                              type: 'string',
                              id: 2,
                            },
                            textSide: {
                              type: 'string',
                              id: 3,
                            },
                            dmSge: {
                              type: 'DmSegConfig',
                              id: 4,
                            },
                            flag: {
                              type: 'DanmakuFlagConfig',
                              id: 5,
                            },
                            specialDms: {
                              rule: 'repeated',
                              type: 'string',
                              id: 6,
                            },
                            checkBox: {
                              type: 'bool',
                              id: 7,
                            },
                            count: {
                              type: 'int64',
                              id: 8,
                            },
                            commandDms: {
                              rule: 'repeated',
                              type: 'CommandDm',
                              id: 9,
                            },
                            playerConfig: {
                              type: 'DanmuWebPlayerConfig',
                              id: 10,
                            },
                            reportFilterContent: {
                              rule: 'repeated',
                              type: 'string',
                              id: 11,
                            },
                            expressions: {
                              rule: 'repeated',
                              type: 'Expressions',
                              id: 12,
                            },
                            postPanel: {
                              rule: 'repeated',
                              type: 'PostPanel',
                              id: 13,
                            },
                            activityMeta: {
                              rule: 'repeated',
                              type: 'string',
                              id: 14,
                            },
                          },
                        },
                        ExpoReport: {
                          fields: {
                            shouldReportAtEnd: {
                              type: 'bool',
                              id: 1,
                            },
                          },
                        },
                        ExposureType: {
                          values: {
                            ExposureTypeNone: 0,
                            ExposureTypeDMSend: 1,
                          },
                        },
                        Expression: {
                          fields: {
                            keyword: {
                              rule: 'repeated',
                              type: 'string',
                              id: 1,
                            },
                            url: {
                              type: 'string',
                              id: 2,
                            },
                            period: {
                              rule: 'repeated',
                              type: 'Period',
                              id: 3,
                            },
                          },
                        },
                        Expressions: {
                          fields: {
                            data: {
                              rule: 'repeated',
                              type: 'Expression',
                              id: 1,
                            },
                          },
                        },
                        InlinePlayerDanmakuSwitch: {
                          fields: {
                            value: {
                              type: 'bool',
                              id: 1,
                            },
                          },
                        },
                        Label: {
                          fields: {
                            title: {
                              type: 'string',
                              id: 1,
                            },
                            content: {
                              rule: 'repeated',
                              type: 'string',
                              id: 2,
                            },
                          },
                        },
                        LabelV2: {
                          fields: {
                            title: {
                              type: 'string',
                              id: 1,
                            },
                            content: {
                              rule: 'repeated',
                              type: 'string',
                              id: 2,
                            },
                            exposureOnce: {
                              type: 'bool',
                              id: 3,
                            },
                            exposureType: {
                              type: 'int32',
                              id: 4,
                            },
                          },
                        },
                        Period: {
                          fields: {
                            start: {
                              type: 'int64',
                              id: 1,
                            },
                            end: {
                              type: 'int64',
                              id: 2,
                            },
                          },
                        },
                        PlayerDanmakuAiRecommendedLevel: {
                          fields: {
                            value: {
                              type: 'bool',
                              id: 1,
                            },
                          },
                        },
                        PlayerDanmakuAiRecommendedLevelV2: {
                          fields: {
                            value: {
                              type: 'int32',
                              id: 1,
                            },
                          },
                        },
                        PlayerDanmakuAiRecommendedSwitch: {
                          fields: {
                            value: {
                              type: 'bool',
                              id: 1,
                            },
                          },
                        },
                        PlayerDanmakuBlockbottom: {
                          fields: {
                            value: {
                              type: 'bool',
                              id: 1,
                            },
                          },
                        },
                        PlayerDanmakuBlockcolorful: {
                          fields: {
                            value: {
                              type: 'bool',
                              id: 1,
                            },
                          },
                        },
                        PlayerDanmakuBlockrepeat: {
                          fields: {
                            value: {
                              type: 'bool',
                              id: 1,
                            },
                          },
                        },
                        PlayerDanmakuBlockscroll: {
                          fields: {
                            value: {
                              type: 'bool',
                              id: 1,
                            },
                          },
                        },
                        PlayerDanmakuBlockspecial: {
                          fields: {
                            value: {
                              type: 'bool',
                              id: 1,
                            },
                          },
                        },
                        PlayerDanmakuBlocktop: {
                          fields: {
                            value: {
                              type: 'bool',
                              id: 1,
                            },
                          },
                        },
                        PlayerDanmakuDomain: {
                          fields: {
                            value: {
                              type: 'float',
                              id: 1,
                            },
                          },
                        },
                        PlayerDanmakuEnableblocklist: {
                          fields: {
                            value: {
                              type: 'bool',
                              id: 1,
                            },
                          },
                        },
                        PlayerDanmakuOpacity: {
                          fields: {
                            value: {
                              type: 'float',
                              id: 1,
                            },
                          },
                        },
                        PlayerDanmakuScalingfactor: {
                          fields: {
                            value: {
                              type: 'float',
                              id: 1,
                            },
                          },
                        },
                        PlayerDanmakuSeniorModeSwitch: {
                          fields: {
                            value: {
                              type: 'int32',
                              id: 1,
                            },
                          },
                        },
                        PlayerDanmakuSpeed: {
                          fields: {
                            value: {
                              type: 'int32',
                              id: 1,
                            },
                          },
                        },
                        PlayerDanmakuSwitch: {
                          fields: {
                            value: {
                              type: 'bool',
                              id: 1,
                            },
                            canIgnore: {
                              type: 'bool',
                              id: 2,
                            },
                          },
                        },
                        PlayerDanmakuSwitchSave: {
                          fields: {
                            value: {
                              type: 'bool',
                              id: 1,
                            },
                          },
                        },
                        PlayerDanmakuUseDefaultConfig: {
                          fields: {
                            value: {
                              type: 'bool',
                              id: 1,
                            },
                          },
                        },
                        PostPanel: {
                          fields: {
                            start: {
                              type: 'int64',
                              id: 1,
                            },
                            end: {
                              type: 'int64',
                              id: 2,
                            },
                            priority: {
                              type: 'int64',
                              id: 3,
                            },
                            bizId: {
                              type: 'int64',
                              id: 4,
                            },
                            bizType: {
                              type: 'PostPanelBizType',
                              id: 5,
                            },
                            clickButton: {
                              type: 'ClickButton',
                              id: 6,
                            },
                            textInput: {
                              type: 'TextInput',
                              id: 7,
                            },
                            checkBox: {
                              type: 'CheckBox',
                              id: 8,
                            },
                            toast: {
                              type: 'Toast',
                              id: 9,
                            },
                          },
                        },
                        PostPanelBizType: {
                          values: {
                            PostPanelBizTypeNone: 0,
                            PostPanelBizTypeEncourage: 1,
                            PostPanelBizTypeColorDM: 2,
                            PostPanelBizTypeNFTDM: 3,
                            PostPanelBizTypeFragClose: 4,
                            PostPanelBizTypeRecommend: 5,
                          },
                        },
                        PostPanelV2: {
                          fields: {
                            start: {
                              type: 'int64',
                              id: 1,
                            },
                            end: {
                              type: 'int64',
                              id: 2,
                            },
                            bizType: {
                              type: 'int32',
                              id: 3,
                            },
                            clickButton: {
                              type: 'ClickButtonV2',
                              id: 4,
                            },
                            textInput: {
                              type: 'TextInputV2',
                              id: 5,
                            },
                            checkBox: {
                              type: 'CheckBoxV2',
                              id: 6,
                            },
                            toast: {
                              type: 'ToastV2',
                              id: 7,
                            },
                            bubble: {
                              type: 'BubbleV2',
                              id: 8,
                            },
                            label: {
                              type: 'LabelV2',
                              id: 9,
                            },
                            postStatus: {
                              type: 'int32',
                              id: 10,
                            },
                          },
                        },
                        PostStatus: {
                          values: {
                            PostStatusNormal: 0,
                            PostStatusClosed: 1,
                          },
                        },
                        RenderType: {
                          values: {
                            RenderTypeNone: 0,
                            RenderTypeSingle: 1,
                            RenderTypeRotation: 2,
                          },
                        },
                        Response: {
                          fields: {
                            code: {
                              type: 'int32',
                              id: 1,
                            },
                            message: {
                              type: 'string',
                              id: 2,
                            },
                          },
                        },
                        SubtitleAiStatus: {
                          values: {
                            None: 0,
                            Exposure: 1,
                            Assist: 2,
                          },
                        },
                        SubtitleAiType: {
                          values: {
                            Normal: 0,
                            Translate: 1,
                          },
                        },
                        SubtitleItem: {
                          fields: {
                            id: {
                              type: 'int64',
                              id: 1,
                            },
                            idStr: {
                              type: 'string',
                              id: 2,
                            },
                            lan: {
                              type: 'string',
                              id: 3,
                            },
                            lanDoc: {
                              type: 'string',
                              id: 4,
                            },
                            subtitleUrl: {
                              type: 'string',
                              id: 5,
                            },
                            author: {
                              type: 'UserInfo',
                              id: 6,
                            },
                            type: {
                              type: 'SubtitleType',
                              id: 7,
                            },
                            lanDocBrief: {
                              type: 'string',
                              id: 8,
                            },
                            aiType: {
                              type: 'SubtitleAiType',
                              id: 9,
                            },
                            aiStatus: {
                              type: 'SubtitleAiStatus',
                              id: 10,
                            },
                          },
                        },
                        SubtitleType: {
                          values: {
                            CC: 0,
                            AI: 1,
                          },
                        },
                        TextInput: {
                          fields: {
                            portraitPlaceholder: {
                              rule: 'repeated',
                              type: 'string',
                              id: 1,
                            },
                            landscapePlaceholder: {
                              rule: 'repeated',
                              type: 'string',
                              id: 2,
                            },
                            renderType: {
                              type: 'RenderType',
                              id: 3,
                            },
                            placeholderPost: {
                              type: 'bool',
                              id: 4,
                            },
                            show: {
                              type: 'bool',
                              id: 5,
                            },
                            avatar: {
                              rule: 'repeated',
                              type: 'Avatar',
                              id: 6,
                            },
                            postStatus: {
                              type: 'PostStatus',
                              id: 7,
                            },
                            label: {
                              type: 'Label',
                              id: 8,
                            },
                          },
                        },
                        TextInputV2: {
                          fields: {
                            portraitPlaceholder: {
                              rule: 'repeated',
                              type: 'string',
                              id: 1,
                            },
                            landscapePlaceholder: {
                              rule: 'repeated',
                              type: 'string',
                              id: 2,
                            },
                            renderType: {
                              type: 'RenderType',
                              id: 3,
                            },
                            placeholderPost: {
                              type: 'bool',
                              id: 4,
                            },
                            avatar: {
                              rule: 'repeated',
                              type: 'Avatar',
                              id: 5,
                            },
                            textInputLimit: {
                              type: 'int32',
                              id: 6,
                            },
                          },
                        },
                        Toast: {
                          fields: {
                            text: {
                              type: 'string',
                              id: 1,
                            },
                            duration: {
                              type: 'int32',
                              id: 2,
                            },
                            show: {
                              type: 'bool',
                              id: 3,
                            },
                            button: {
                              type: 'Button',
                              id: 4,
                            },
                          },
                        },
                        ToastButtonV2: {
                          fields: {
                            text: {
                              type: 'string',
                              id: 1,
                            },
                            action: {
                              type: 'int32',
                              id: 2,
                            },
                          },
                        },
                        ToastFunctionType: {
                          values: {
                            ToastFunctionTypeNone: 0,
                            ToastFunctionTypePostPanel: 1,
                          },
                        },
                        ToastV2: {
                          fields: {
                            text: {
                              type: 'string',
                              id: 1,
                            },
                            duration: {
                              type: 'int32',
                              id: 2,
                            },
                            toastButtonV2: {
                              type: 'ToastButtonV2',
                              id: 3,
                            },
                          },
                        },
                        UserInfo: {
                          fields: {
                            mid: {
                              type: 'int64',
                              id: 1,
                            },
                            name: {
                              type: 'string',
                              id: 2,
                            },
                            sex: {
                              type: 'string',
                              id: 3,
                            },
                            face: {
                              type: 'string',
                              id: 4,
                            },
                            sign: {
                              type: 'string',
                              id: 5,
                            },
                            rank: {
                              type: 'int32',
                              id: 6,
                            },
                          },
                        },
                        VideoMask: {
                          fields: {
                            cid: {
                              type: 'int64',
                              id: 1,
                            },
                            plat: {
                              type: 'int32',
                              id: 2,
                            },
                            fps: {
                              type: 'int32',
                              id: 3,
                            },
                            time: {
                              type: 'int64',
                              id: 4,
                            },
                            maskUrl: {
                              type: 'string',
                              id: 5,
                            },
                          },
                        },
                        VideoSubtitle: {
                          fields: {
                            lan: {
                              type: 'string',
                              id: 1,
                            },
                            lanDoc: {
                              type: 'string',
                              id: 2,
                            },
                            subtitles: {
                              rule: 'repeated',
                              type: 'SubtitleItem',
                              id: 3,
                            },
                          },
                        },
                      },
                    },
                  },
                },
              },
            },
          },
        },
      },
    },
  },
} as any
