<template>
  <div class="loading">
    <div class="loadingio-spinner-dual-ring-zjobdtwe9oe"><div class="ldio-6yqx4gpvkkt">
    <div></div><div><div></div></div>
    </div></div>
  </div>
</template>
<style scoped>
.loading {
  transform: scale(.4);
  transform-origin: center;
  text-align: center;
  position: relative;
  top: -40px;
}
@keyframes ldio-6yqx4gpvkkt {
  0% { transform: rotate(0) }
  100% { transform: rotate(360deg) }
}
.ldio-6yqx4gpvkkt div { box-sizing: border-box!important }
.ldio-6yqx4gpvkkt > div {
  position: absolute;
  width: 144px;
  height: 144px;
  top: 28px;
  left: 28px;
  border-radius: 50%;
  border: 16px solid #000;
  border-color: #fe718d transparent #fe718d transparent;
  animation: ldio-6yqx4gpvkkt 1s linear infinite;
}
.ldio-6yqx4gpvkkt > div:nth-child(2) { border-color: transparent }
.ldio-6yqx4gpvkkt > div:nth-child(2) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-6yqx4gpvkkt > div:nth-child(2) div:before, .ldio-6yqx4gpvkkt > div:nth-child(2) div:after { 
  content: "";
  display: block;
  position: absolute;
  width: 16px;
  height: 16px;
  top: -16px;
  left: 48px;
  background: #fe718d;
  border-radius: 50%;
  box-shadow: 0 128px 0 0 #fe718d;
}
.ldio-6yqx4gpvkkt > div:nth-child(2) div:after { 
  left: -16px;
  top: 48px;
  box-shadow: 128px 0 0 0 #fe718d;
}
.loadingio-spinner-dual-ring-zjobdtwe9oe {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-6yqx4gpvkkt {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-6yqx4gpvkkt div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>
